version: "3.5"

services:

  api:
    image: adouglas/interview-app:latest
    depends_on:
      - mysql-db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/definitions?useSSL=false

  mysql-db:
    image: mysql:5
    ports:
      - 3406:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50